batch_size: 128
env: LunarLanderContinuous-v2
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 10000
freqTest: 20
freqVerbose: 10000
fromFile: null
gamma: 0.99
lr_mu: 0.0005
lr_q: 0.001
nbEpisodes: 3000
nbTest: 3
seed: 5
tau: 0.005
