K_epoch: 5
T_horizon: 40
Trajectory_size: 10
comment: version with longer T_horizon
delta: 0.01
env: LunarLander-v2
eps_clip: 0.1
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 10000
freqTest: 5
freqVerbose: 10000
fromFile: null
gamma: 0.98
learning_rate: 0.0005
lmbda: 0.95
nbEpisodes: 3000
nbTest: 1
seed: 5
