batch_size: 128
env: LunarLanderContinuous-v2
epsilon_mu: 0.0005
epsilon_q: 0.001
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 10000
freqTest: 20
freqVerbose: 10000
fromFile: null
gamma: 0.99
nbEpisodes: 3000
nbTest: 3
ro: 0.005
seed: 5
