batch_size: 256
capacity: 100000
env: simple_spread
eploration_phase: 100
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 10000
freqTest: 20
freqVerbose: 10000
fromFile: null
max_steps: 100
n_episode: 1000
nbActions: 2
nbEtats: 14
nbTest: 5
seed: 5
update_frequency: 2000
