env: gridworld-v0
map: gridworldPlans/plan0.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor2 ''
freqSave: 10000
freqTest: 5
nbTest: 1
freqVerbose: 10000
fromFile: null
nbEpisodes: 5000
Trajectory_size: 10
