env: CartPole-v1
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 10000
freqTest: 20
nbTest: 5
freqVerbose: 10000
fromFile: null
nbEpisodes: 3000
gamma: 0.98
alpha: 0.0002
update_frequency : 2000
Trajectory_size: 10
