env: LunarLanderContinuous-v2
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 10000
freqTest: 20
nbTest: 3
freqVerbose: 10000
fromFile: null
nbEpisodes: 3000
epsilon_mu        : 0.0005
epsilon_q         : 0.001
gamma        : 0.99
batch_size   : 128
ro          : 0.005
