K_epoch: 5
T_horizon: 40
Trajectory_size: 10
comment: version exactement comme cart
delta: 0.01
env: LunarLanderContinuous-v2
eps_clip: 0.1
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 10000
freqTest: 20
freqVerbose: 10000
fromFile: null
gamma: 0.98
learning_rate: 0.0005
lmbda: 0.95
nbEpisodes: 3000
nbTest: 3
seed: 5
