env: gridworld-v0
map: gridworldPlans/plan0.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor2 ''
freqSave: 10000
freqTest: 5
nbTest: 5
freqVerbose: 10000
fromFile: null
nbEpisodes: 5000
alpha : 0.0005
gamma : 0.98
lmbda: 0.95
epsilon: 0.2
K : 3
t_step: 40
delta: 0.01
entropy_weight: 0.01
